### ISSUE TITLE
Profile location for Tor Browser

### ISSUE THREAD

**Issue by fturco** [graysky2/profile-cleaner#19]
On my system `profile-cleaner` doesn't detect Tor Browser's profile:

```
$ profile-cleaner to
profile-cleaner v2.35

Error: no profile directory for torbrowser found.
```

The following command works instead:

```
$ profile-cleaner p ~/.mozilla/torbrowser
profile-cleaner v2.35

 Cleaning places.sqlite                        done  -0 Mbytes
 Cleaning content-prefs.sqlite                 done  -0 Mbytes
 Cleaning cookies.sqlite                       done  -0 Mbytes
 Cleaning webappsstore.sqlite                  done  -0 Mbytes

 Profile(s) for paths reduced by 0 Mbytes.
```

My distribution is Gentoo Linux.

Packages:
- `www-client/torbrowser-45.4.0_p605` (from the `torbrowser` overlay)
- `app-admin/profile-cleaner-2.35` (from the `laurentb` overlay)

**Comment by graysky2** [comment]
Yes, it seems there are some inconsistencies across distros with respect to profile location of torbrowser.  Gentoo, it seems, is placing it under `~/.mozilla/torbrowser` while Arch puts it under `~/.tor-browser-$lang` where lang=whatever locale is installed.  I need to check where some of the other distros put it to confirm the inconsistency.
