### ISSUE TITLE
Debian: GPG Error - NO_PUBKEY

### ISSUE THREAD

**Issue by keypey** [graysky2/profile-cleaner#22]
Hi.

Updating the repository generates an error (apt-get update):
`In: GPG Error: http://ppa.launchpad.net quantal Release: The following signatures could not be verified due to lack of public key: NO_PUBKEY C1C5C63BF0E0B4E7`

Debian 8  (LMDE Betsy) [Linux blmde 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux].

**Comment by graysky2** [comment]
Ah, ever since psd as accepted into the Debian repos, I haven't been doing much w/ the PPA.  I will look into this.

**Comment by kepi** [comment]
In my case (debian unstable) error was "repository ... quantal Release is not signed."

Changing `quantal` in sources list to `zetsy` fixed it

**Comment by keypey** [comment]
I change repo to quantal and add key
`W: Błąd GPG: http://ppa.launchpad.net/graysky/utils/ubuntu quantal Release: Następujące podpisy nie mogły zostać zweryfikowane z powodu braku klucza publicznego: NO_PUBKEY C1C5C63BF0E0B4E7
E: The repository 'http://ppa.launchpad.net/graysky/utils/ubuntu quantal Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

Linux thinkc 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux,
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
