### ISSUE TITLE
Gentoo install updates

### ISSUE THREAD

**Issue by hartwork** [graysky2/profile-cleaner#23]
Hi!

Gentoo install instructions currently read:
```
layman -a laurentb
emerge profile-cleaner
```
profile-cleaner is available in the Gentoo main repository by now, i.e. the `laurentb` overlay is no longer needed for this very task.
With some extra polishing on top, this is what I recommend for 2017-05 Gentoo instructions:
```
sudo emerge -av app-admin/profile-cleaner
```
Thanks and best

Sebastian

**Comment by graysky2** [comment]
https://github.com/graysky2/profile-cleaner/commit/0f2d1a69fea23f0e9be20099d0e3c678df2e74bd

Thanks

**Comment by hartwork** [comment]
That was quick, thanks!
