### ISSUE TITLE
Support for Falkon

### ISSUE THREAD

**Issue by fturco** [graysky2/profile-cleaner#24]
QupZilla is now known as Falkon: https://davidrosca.blogspot.it/2018/02/falkon-300-released.html

The profile is in `~/.config/falkon/` instead of `~/.config/qupzilla/`.

**Comment by graysky2** [comment]
I don't have falkon installed so please try this commit and get back to me.

**Comment by fturco** [comment]
It doesn't work. The exact path is `~/.config/falkon/profiles`, not simply `~/.config/falkon`. Just like QupZilla. Moreover by running `profile-cleaner` without any arguments, Falkon is not listed as an option.

**Comment by graysky2** [comment]
Opps, please try https://github.com/graysky2/profile-cleaner/commit/aef546589936a658d4abd65bdbfd5b03fecee8a9

**Comment by fturco** [comment]
Now it works. Thank you!
