### ISSUE TITLE
[Feature Request] Support for Vivaldi

### ISSUE THREAD

**Issue by simonbcn** [graysky2/profile-cleaner#25]
Support for Vivaldi: https://vivaldi.com
Thanks

**Comment by Vistaus** [comment]
I second this.

**Comment by jorgicio** [comment]
If it would be of help to you, I just created this patch in order to support Vivaldi browser, stable and snapshot.
https://gist.github.com/jorgicio/f1f38e10743a2403318cad9154437ea2

**Comment by graysky2** [comment]
3f02d919807cacbc21e2b56f2df936554805857a

**Comment by Vistaus** [comment]
> [3f02d91](https://github.com/graysky2/profile-cleaner/commit/3f02d919807cacbc21e2b56f2df936554805857a)

It doesn't seem to be working :/

```
 18:19:04  ✘  ~/Downloads/profile-cleaner   master ✔ 
$ profile-cleaner v                                                                                                                                                                  06:19:04  
profile-cleaner v2.38

Error: no profile directory for vivaldi found.

 18:19:10  ✘  ~/Downloads/profile-cleaner   master ✔ 
$  
```

**Comment by jorgicio** [comment]
Name of the directory file (in $HOME/.config) is Vivaldi or vivaldi? May be is this the issue.

**Comment by graysky2** [comment]
Worked for me with [vivaldi](https://aur.archlinux.org/packages/vivaldi/) on Arch.
```
% pc v
profile-cleaner v@VERSION@

 Cleaning profile for vivaldi
 Cleaning Calendar                             done  -0 Mbytes
 Cleaning Web Data                             done  -0 Mbytes
 Cleaning heavy_ad_intervention_opt_out.db     done  -0 Mbytes
 Cleaning Cookies                              done  -0 Mbytes
 Cleaning History                              done  -0 Mbytes
 Cleaning Network Action Predictor             done  -0 Mbytes
 Cleaning Login Data                           done  -0 Mbytes
 Cleaning Contacts                             done  -0 Mbytes
 Cleaning Top Sites                            done  -0 Mbytes
 Cleaning Favicons                             done  -0 Mbytes
 Cleaning Reporting and NEL                    done  -0 Mbytes
 Cleaning previews_opt_out.db                  done  -0 Mbytes

 Profile(s) for vivaldi reduced by 0 Mbytes.
```

**Comment by Vistaus** [comment]
> Name of the directory file (in $HOME/.config) is Vivaldi or vivaldi? May be is this the issue.

The config folder vivaldi-snapshot is in $HOME/.config, so it should be able to find it...

**Comment by graysky2** [comment]
I see what's happening ... one sec

**Comment by graysky2** [comment]
Please try https://github.com/graysky2/profile-cleaner/commit/c2ca858c9851e907e639510b41ad62baa83fc4e6

**Comment by graysky2** [comment]
Fixed. Please try https://github.com/graysky2/profile-cleaner/releases/tag/v2.40

**Comment by Vistaus** [comment]
Yes, that fixed it. Cheers, mate! :)
