### ISSUE TITLE
error in installation on mint 18.2

### ISSUE THREAD

**Issue by admzzz** [graysky2/profile-cleaner#26]
Preparing to unpack .../profile-cleaner_2.36-1_all.deb ...
Unpacking profile-cleaner (2.36-1) ...
Processing triggers for systemd (229-4ubuntu21.1) ...
Processing triggers for doc-base (0.10.7) ...
Processing 62 changed doc-base files, 2 added doc-base files...
Error in `/usr/share/doc-base/xapian-python3-docs', line 9: all `Format' sections are invalid.
Note: `install-docs --verbose --check file_name' may give more details about the above error.
Registering documents with scrollkeeper...
Processing triggers for man-db (2.7.5-1) ...
Setting up sysstat (11.2.0-1ubuntu0.2) ...

Creating config file /etc/default/sysstat with new version
update-alternatives: using /usr/bin/sar.sysstat to provide /usr/bin/sar (sar) in auto mode
Setting up parallel (20141022+ds1-1) ...
Setting up profile-cleaner (2.36-1) ...
--------------------------------------------------------------------------
  Make sure that target browsers or email clients are not running when
  invoking profile-cleaner. Failure to do so will result in the open files
  NOT getting cleaned and reindexed.

  $HOME/.config/profile-cleaner.conf will be created when the script is
  called to run the first time. Edit it to select a color scheme.
--------------------------------------------------------------------------
Processing triggers for systemd (229-4ubuntu21.1) ...
wwwadm admz # install-docs --verbose --check /usr/share/doc-base/xapian-python3-docs
Warning in `/usr/share/doc-base/xapian-python3-docs', line 9: file `/usr/share/doc/python3-xapian1.3/index.html' does not exist.
Error in `/usr/share/doc-base/xapian-python3-docs', line 9: all `Format' sections are invalid.
/usr/share/doc-base/xapian-python3-docs: Fatal error found, the file won't be registered.
wwwadm admz #

**Comment by graysky2** [comment]
Please try with current version and open if still a problem
