### ISSUE TITLE
Support for Newsboat

### ISSUE THREAD

**Issue by Dr-Terrible** [graysky2/profile-cleaner#27]
Newsbeuter has been abandoned by upstream and has been forked as Newsboat: https://github.com/akrennmair/newsbeuter/blob/7c981f460d6c8c3690f140cbb279c277dc8f55fe/README.md

The profile is in `~/.local/share/newsboat` instead of `~/.local/share/newsbeuter`.

p.s.: Newsboat is maintaing compatibility with the original sqlite3 schemas from Newsbeuter

**Comment by graysky2** [comment]
20cdecf4accc2fb36df08b6632fd310fba649b1c
