### ISSUE TITLE
Not working on Debian 10

### ISSUE THREAD

**Issue by Vistaus** [graysky2/profile-cleaner#31]
I compiled the latest git master, but it's not working. It says "I require bc but it's not installed. Aborting."

But bc is correctly installed in /usr/bin

Any idea how to figure out what's wrong here? :)

**Comment by graysky2** [comment]
Guessing you're missing `parallel` but I forgot to substitute "bc" for "$dep" in that line so it incorrectly printed that.  Please pull latest comment and try again.

**Comment by Vistaus** [comment]
Yes, problem solved. Thanks for the quick reply and fix :)
