### ISSUE TITLE
Fix Brave support

### ISSUE THREAD

**Issue by jorgicio** [graysky2/profile-cleaner#32]
Hi! Thanks for adding Brave support, but paths are kinda wrong. Also, there are more branches of Brave to keep in mind.
I just created this patch to solve this issue.

Thanks!

https://gist.github.com/jorgicio/c804949393c5f9e0ef9c5c22996e4f58

**Comment by graysky2** [comment]
Mind sending a PR?

**Comment by jorgicio** [comment]
Thank you, but after solving #25 with Vivaldi, it broke Brave support again.
Now it says this:
`hackenherr:profile-cleaner jorgicio% pc b                                                                                         [12:33:18]
profile-cleaner v2.40

 Cleaning profile for BraveSoftware/Brave-Browser
Usage: file [-bcCdEhikLlNnprsvzZ0] [--apple] [--extension] [--mime-encoding]
            [--mime-type] [-e <testname>] [-F <separator>]  [-f <namefile>]
            [-m <magicfiles>] [-P <parameter=value>] <file> ...
       file -C [-m <magicfiles>]
       file [--help]

 Profile(s) for BraveSoftware/Brave-Browser reduced by 0 Mbytes.
`

Note that, unlike other Chrome-based browsers, paths for Brave configuration are different because there's inside another directory. For example, in the stable branch, the path is:
$XDG_CONFIG_HOME/BraveSoftware/Brave

Thanks!

**Comment by graysky2** [comment]
@jorgicio - Fixed.  Please try https://github.com/graysky2/profile-cleaner/releases/tag/v2.41

**Comment by jorgicio** [comment]
Issue fixed. Thank you very much!

**Comment by graysky2** [comment]
@jorgicio - Thanks for reporting.
