### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by e-t-l** [graysky2/profile-cleaner#46]
Is there a way (or could I help you create a way) to apply this to Windows installations of Firefox?
I see 3 basic ways it could be implemented, in order of descending difficulty:
1. Port profile-cleaner to run natively on Windows. (Needs to include ports of the necessary dependencies)
2. Run profile-cleaner in Windows Subsystem for Linux, which can access the Windows filesystem. (I think this would mainly involve adjusting the filepaths?)
3. User copies Firefox profile into Linux VM, runs Profile-cleaner, and copies it back. (I don't know if directory structure is identical between Windows installation and Linux installation)

I think Option 2 is the most reasonable one, but I'm interested to hear your thoughts about this!

**Comment by graysky2** [comment]
Sorry, I haven't used windows in years and have no access to a copy for testing.
